services:
   ny-trainer:
    image: ny-trainer:latest
    container_name: ny-trainer
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=4,5,6,7
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - /mnt/nvme:/app/data
      - /home/ubuntu/workspace/nyoung:/app/workspace
      - /etc/localtime:/etc/localtime:ro
    shm_size: '64g'
    cap_add:
      - SYS_ADMIN
